### ISSUE TITLE
Move oxi-tests to root tests dir

### ISSUE THREAD

**Issue by shift-d** [noib3/nvim-oxi#21]
Currently CI does not show us the fact that tests are failing because oxi-tests is excluded from cargo workspace. I will create a PR that fixes this behavior by cding into oxi-tests dir, although the better approach would be extracting tests from a crate and moving to actual tests dir.

[more info about tests/](https://doc.rust-lang.org/book/ch11-03-test-organization.html#the-tests-directory)

**Comment by noib3** [comment]
> the better approach would be extracting tests from a crate and moving to actual tests dir

Unfortunately it's not that easy, marking a test with `#[test]` doesn't really work to test the functions from inside Neovim.

In order to test `nvim-oxi` we first have to compile a C dynamic library that Neovim can import and execute. I've explained the situation in much more detail [here](https://users.rust-lang.org/t/how-do-you-test-a-library-imported-by-another-program/76483).

**Comment by shift-d** [comment]
hmmm, i see now, thanks. I will close this issue now
