### ISSUE TITLE
Reason for not using mlua

### ISSUE THREAD

**Issue by Maan2003** [noib3/nvim-oxi#26]
For most neovim plugin, interop with Lua is crucial. mlua seems to pretty good at that. What is rationale behind reinvented the wheel here?

**Comment by noib3** [comment]
The two main reasons are:

- performance: when using mlua you're calling the Neovim Lua api, i.e. Lua bindings to the C api. This means that all the Rust values are first converted to Lua values, then you call the Lua api, then Neovim converts those values back to C.

Since all the Neovim C functions are exported we can avoid all of that by hooking straight into the C api via ffi, effectively turning

```
Rust -> Lua, Lua -> C
```
into
```
Rust -> C
```

- integration: mlua is a fantastic crate, but it is a *general purpose* one. I believe there's a lot of value in having a more vertically integrated framework that's tailored specifically to Neovim, allowing you to take full advantage of Rusty's type system. Examples are still scarce since `nvim-oxi` is still far from ready but you'll see what I mean.

**Comment by Maan2003** [comment]
I didn't explain the question properly. I understand using neovim C functions directly.

But I don't understand why we are using lua C function directly (in nvim-oxi/src/lua). It is hard to get correct and just creates additional work.

**Comment by noib3** [comment]
> we are using lua C function directly (in nvim-oxi/src/lua)

We don't? I'm not sure what you mean by "lua C function". Could you link the module/line?

**Comment by Maan2003** [comment]
these 
https://github.com/noib3/nvim-oxi/blob/de5afb5807469fa0f10f20f7dcf448321c3e0578/nvim-oxi/src/lua/ffi.rs#L45-L53

**Comment by noib3** [comment]
Yes, those are needed.

**Comment by Maan2003** [comment]
> Yes, those are needed.

Yes that is question, why deal with unsafe ffi ourselves, instead of using mlua in module mode.
