### ISSUE TITLE
How to get return from an async function

### ISSUE THREAD

**Issue by Avimitin** [noib3/nvim-oxi#57]
Inspired by your crate, I want to use Rust to provide completion list for the `cargo add` command so that user can easily get available version when they type `@` and get available features when they input `-F` through the neovim command line.

 I have wrote some simple code to get crate information from crates.io, but now I stuck at not knowing how to return result from async function.

Here is my current implementation: https://github.com/Avimitin/cargo-add-cmp.nvim/blob/master/src/lib.rs#L99. I don't know how to await it and return the list of result as Lua api.

**Comment by noib3** [comment]
Check out [this](https://github.com/noib3/nvim-oxi/blob/master/examples/libuv.rs#L43-L70) example.

**Comment by Avimitin** [comment]
Sorry for bothering you, but I am still feeling confused about some details:

1. Is this thread keep running with the neovim(the example seems like it is running as a background daemon), if it is, is that mean that I need to handle the thread management?
2. The completion list need a function (`fn (String, String, usize) -> Vec<String>`) to return list of completions, I still can't find out a way to achieve this approach (unless I block the async code, but I don't know if it will block the command line)

**Comment by noib3** [comment]
1. the spawned thread will run until completion (in the example I linked it never completes because of the `loop {..}`). I'm not sure what you mean by "thread management". If you don't care about the return value of the spawned thread (`()` in the example), you can just drop the `thread::JoinHandle`,

2. I'm not really sure what you're trying to do tbh. Who's gonna call that function at runtime? If it gets called by Lua you have to block the UI thread. If you're provided a callback that you can use when you have the result you need (probably coming from some async IO if you're using tokio) then you can spawn a new thread, do your IO there, send the result to the main thread when you're done and trigger the function that you need to run via `AsyncHandle::send`.

**Comment by Avimitin** [comment]
Thanks for your patient guidance, I will try to implement this.

**Comment by noib3** [comment]
I'll close this issue, if you're still experiencing problems feel free to open a new discussion.
